import type { Metadata } from "next";
import PostList from "./posts/components/PostList";

export const metadata: Metadata = {
  title: "Your part App",
  description: "Generated by Your part app",
};
export default function Home() {
  return <PostList />;
}
